
export const flags = {
  algeria: require('../assets/jogos/Algeria.png'),
  ARG: require('../assets/jogos/argentina.png'),
  AUS: require('../assets/jogos/australia.png'),
  BEL: require('../assets/jogos/belgium.png'),
  BOL: require('../assets/jogos/bolivia.png'),
  BRA: require('../assets/jogos/brazil.png'),
  CAM: require('../assets/jogos/cameroon.png'),
  CAN: require('../assets/jogos/canada.png'),
  chile: require('../assets/jogos/chile.png'),
  colombia: require('../assets/jogos/colombia.png'),
  costa_rica: require('../assets/jogos/costa rica.png'),
  croatia: require('../assets/jogos/croatia.png'),
  denmark: require('../assets/jogos/denmark.png'),
  ecuador: require('../assets/jogos/ecuador.png'),
  egypt: require('../assets/jogos/egypt.png'),
  england: require('../assets/jogos/england.png'),
  france: require('../assets/jogos/france.png'),
  germany: require('../assets/jogos/germany.png'),
  ghana: require('../assets/jogos/ghana.png'),
  iran: require('../assets/jogos/iran.png'),
  iraq: require('../assets/jogos/iraq.png'),
  italy: require('../assets/jogos/italy.png'),
  ivory_coast: require('../assets/jogos/ivory coast.png'),
  jamaica: require('../assets/jogos/jamaica.png'),
  japan: require('../assets/jogos/japan.png'),
  mali: require('../assets/jogos/mali.png'),
  MEX: require('../assets/jogos/mexico.png'),
  morocco: require('../assets/jogos/morocco.png'),
  netherlands: require('../assets/jogos/netherlands.png'),
  new_zealand: require('../assets/jogos/new zealand.png'),
  nigeria: require('../assets/jogos/nigeria.png'),
  norway: require('../assets/jogos/norway.png'),
  panama: require('../assets/jogos/panama.png'),
  paraguay: require('../assets/jogos/paraguay.png'),
  peru: require('../assets/jogos/peru.png'),
  poland: require('../assets/jogos/poland.png'),
  portugal: require('../assets/jogos/portugal.png'),
  qatar: require('../assets/jogos/qatar.png'),
  RSA: require('../assets/jogos/russia.png'),
  saudi_arabia: require('../assets/jogos/saudi arabia.png'),
  senegal: require('../assets/jogos/senegal.png'),
  serbia: require('../assets/jogos/serbia.png'),
  KOR: require('../assets/jogos/south korea.png'),
  PAR: require('../assets/jogos/paraguay.png'),
  spain: require('../assets/jogos/spain.png'),
  sweden: require('../assets/jogos/sweden.png'),
  switzerland: require('../assets/jogos/switzerland.png'),
  tunisia: require('../assets/jogos/tunisia.png'),
  uae: require('../assets/jogos/united arab emirates.png'),
  ukraine: require('../assets/jogos/ukraine.png'),
  uruguay: require('../assets/jogos/uruguay.png'),
  usa: require('../assets/jogos/united states.png'),
  venezuela: require('../assets/jogos/venezuela.png'),
};