
export const flags = {
   ALG: require('../assets/jogos/Algeria.png'),
  ARG: require('../assets/jogos/argentina.png'),
  AUS: require('../assets/jogos/australia.png'),
  AUT: require('../assets/jogos/austria.png'),
  BEL: require('../assets/jogos/belgium.png'),
  BOL: require('../assets/jogos/bolivia.png'),
  BIH: require('../assets/jogos/bosnia and herzegovina.png'),
  BRA: require('../assets/jogos/brazil.png'),
  CAN: require('../assets/jogos/canada.png'),
  COD: require('../assets/jogos/republic of the congo.png'),
  CHI: require('../assets/jogos/chile.png'),
  CIV: require('../assets/jogos/ivory coast.png'),
  CMR: require('../assets/jogos/cameroon.png'),
  CPV: require('../assets/jogos/cape verde.png'),
  COL: require('../assets/jogos/colombia.png'),
  CUW: require('../assets/jogos/curacao.png'),
  CRC: require('../assets/jogos/costa rica.png'),
  CRO: require('../assets/jogos/croatia.png'),
  CZE: require('../assets/jogos/czech republic.png'),
  DEN: require('../assets/jogos/denmark.png'),
  ECU: require('../assets/jogos/ecuador.png'),
  EGY: require('../assets/jogos/egypt.png'),
  ENG: require('../assets/jogos/england.png'),
  ESP: require('../assets/jogos/spain.png'),
  FRA: require('../assets/jogos/france.png'),
  GER: require('../assets/jogos/germany.png'),
  GHA: require('../assets/jogos/ghana.png'),
  GRE: require('../assets/jogos/greece.png'),
  HAI: require('../assets/jogos/haiti.png'),
  HUN: require('../assets/jogos/hungary.png'),
  IRN: require('../assets/jogos/iran.png'),
  IRQ: require('../assets/jogos/iraq.png'),
  ITA: require('../assets/jogos/italy.png'),
  JAM: require('../assets/jogos/jamaica.png'),
  JOR: require('../assets/jogos/jordan.png'),
  JPN: require('../assets/jogos/japan.png'),
  KOR: require('../assets/jogos/south korea.png'),
  KSA: require('../assets/jogos/saudi arabia.png'),
  MAR: require('../assets/jogos/morocco.png'),
  MEX: require('../assets/jogos/mexico.png'),
  MLI: require('../assets/jogos/mali.png'),
  NED: require('../assets/jogos/netherlands.png'),
  NGA: require('../assets/jogos/nigeria.png'),
  NOR: require('../assets/jogos/norway.png'),
  NZL: require('../assets/jogos/new zealand.png'),
  PAN: require('../assets/jogos/panama.png'),
  PAR: require('../assets/jogos/paraguay.png'),
  PER: require('../assets/jogos/peru.png'),
  POL: require('../assets/jogos/poland.png'),
  POR: require('../assets/jogos/portugal.png'),
  QAT: require('../assets/jogos/qatar.png'),
  SCO: require('../assets/jogos/scotland.png'),
  SEN: require('../assets/jogos/senegal.png'),
  SRB: require('../assets/jogos/serbia.png'),
  SWE: require('../assets/jogos/sweden.png'),
  SUI: require('../assets/jogos/switzerland.png'),
  RSA: require('../assets/jogos/russia.png'),
  TUN: require('../assets/jogos/tunisia.png'),
  TUR: require('../assets/jogos/turkey.png'),
  UAE: require('../assets/jogos/united arab emirates.png'),
  UKR: require('../assets/jogos/ukraine.png'),
  URU: require('../assets/jogos/uruguay.png'),
  USA: require('../assets/jogos/united states.png'),
  VEN: require('../assets/jogos/venezuela.png'),
};